version: '3'
volumes:
    db-data:
        driver: local
    elastic-data:
        driver: local
        
services:
    php-fpm:
        build:
            context: ./php-fpm
        ports:
            - 9003:9003
        volumes:
            - ../src:/var/www
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm
        volumes:
            - ../src/:/var/www
            - ./nginx:/etc/nginx/conf.d
    postgres:
        restart: always
        image: postgres:9
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=app
        ports:
            - ${CONTAINER_DB_PORT:-5432}:5432
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        volumes:
            - elastic-data:/usr/share/elasticsearch/data
        environment:
            - cluster.name=elastic-cluster
            - node.name=elastic-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - cluster.initial_master_nodes=elastic-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports:
            - "9200:9200"
            - "9300:9300"
    workspace:
        build:
            context: ./workspace
        volumes:
            - ../src/:/var/www/
            - ~/.ssh/:/root/.ssh
        ports:
            - "2222:22"